[package]
name = "modforge-app"
version = "2.0.0"
description = "ModForge — 桌游 Mod 开发 IDE"
authors = ["hty"]
edition = "2021"

[lib]
name = "modforge_app_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-opener = "2"
tauri-plugin-dialog = "2.7.1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
regex = "1"
sha2 = "0.10"
